services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: sportbook_db
      POSTGRES_USER: sportbook
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: