spring:

  profiles:
    default: local
  application:
    name: sportbook
  datasource:
    url: ${POSTGRES_DB_URL:jdbc:h2:mem:sportbook}
    jdbc-url: ${POSTGRES_DB_URL:jdbc:h2:mem:sportbook}
    driver-class-name: ${POSTGRES_DB_DRIVER:org.h2.Driver}
    username: ${POSTGRES_DB_USER:sa}
    password: ${POSTGRES_DB_PASSWORD:}
  jpa:
    show-sql: true
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"

security:
  jwt:
    secret-key: ${SECRET_KEY:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
    expiration-time: 24h

server:
  port: 8080
  servlet:
    context-path: /sportbook
  error:
    include-message: always
    include-binding-errors: always
