spring:
  profiles:
    default: local
  application:
    name: sportbook
  datasource:
    url: ${POSTGRES_DB_URL:jdbc:h2:mem:sportbook}
    jdbc-url: ${POSTGRES_DB_URL:jdbc:h2:mem:sportbook}
    driver-class-name: ${POSTGRES_DB_DRIVER:org.h2.Driver}
    username: ${POSTGRES_DB_USER:sa}
    password: ${POSTGRES_DB_PASSWORD:}
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  servlet:
    context-path: /sportbook
