spring:
  profiles:
    default: local
  application:
    name: sportbook
  datasource:
    jdbc-url: jdbc:h2:mem:sportbook
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


server:
  port: 8080
  servlet:
    context-path: /sportbook
